---
# DOCS: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
language: ruby

cache: bundler

before_install:
  # Bundler 2.0
  - yes | gem update --system --force
  - gem install bundler -v 2.1.2

rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0

script:
  - bundle exec rspec

# DOCS: https://gist.github.com/maxpou/bc3eb944aa727d352f85bc0ce8bc082c
deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: sdoc
  on:
    branch: master
